sudo: false
branches:
  only:
    - master

os: linux
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8
      - libeigen3-dev

script:
  - echo "Installing doxygen"
  - DOXYGEN_VER=doxygen-1.8.15
  - DOXYGEN_TAR=${DOXYGEN_VER}.linux.bin.tar.gz
  - DOXYGEN_URL="http://doxygen.nl/files/${DOXYGEN_TAR}"
  - wget -O - "${DOXYGEN_URL}" | tar xz -C ${TMPDIR-/tmp} ${DOXYGEN_VER}/bin/doxygen
  - export PATH="${TMPDIR-/tmp}/${DOXYGEN_VER}/bin:$PATH"
  - echo "Installed Doxygen"
  - export CC=gcc-8;
  - export CXX=g++-8;
  - ./make.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master