sudo: false
branches:
  only:
    - master

os: linux
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - libeigen3-dev

script:
  - ./make.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master